# Generated by Django 2.2.15 on 2020-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='asd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
